### ISSUE TITLE
Add Light:Dark conversions for more colors

### ISSUE THREAD

**Issue by jp-dubya** [jc9108/dark-mode-pdf#8]
See the example images below. My goal is to convert PDF's to dark mode and then write on them using Samsung Notes on my tablet. Preserving the colors would be ideal, as my professor uses them to highlight important information. Also, I found the white writing slightly difficult to read, it almost blends into the background. I attached a sample pdf in case you want to do some testing with a handwritten document with a variety of colors and some hand-drawn images, attached images and typed text. 
This resource might have suggestions for colors to use: https://material.io/design/color/dark-theme.html#usage

Sample PDF's
[LO Trig Integrals_220606_185218.pdf](https://github.com/jc9108/dark-mode-pdf/files/8848747/LO.Trig.Integrals_220606_185218.pdf)
[Experiment III  Electric Fluxpdf_220606_185434.pdf](https://github.com/jc9108/dark-mode-pdf/files/8848745/Experiment.III.Electric.Fluxpdf_220606_185434.pdf)

Screenshots: 1)Light Mode 2)"Night" Mode 3)Dark Mode. The second image is from a PDF reader which is where I got the idea from. There was no way to convert it permanently though, only view it that way. So your app is awesome!

![image](https://user-images.githubusercontent.com/14313981/172260725-b6ccc9ff-dc74-437f-a645-4418848118a5.png)

![image](https://user-images.githubusercontent.com/14313981/172260760-92ed0f1e-9055-48c6-9e29-a1c40051016f.png)

![image](https://user-images.githubusercontent.com/14313981/172260644-6c3af1b7-5639-47ca-9263-88a36c6c94c4.png)

**Comment by jp-dubya** [comment]
Sample PDF was over 5mb so I grabbed the most interesting pages, and I dark moded it. Even all the drawings/images look good, just colorless:
[samplePDF for dark mode.pdf](https://github.com/jc9108/dark-mode-pdf/files/8848788/samplePDF.for.dark.mode.pdf)
[dark moded sample b&w.pdf](https://github.com/jc9108/dark-mode-pdf/files/8848799/dark.moded.sample.b.w.pdf)

**Comment by jc9108** [comment]
i would guess the way that they do it in the 2nd pic is by utilizing some system display api which is why the result can't be saved to a file (which is something i observed in other pdf readers that can do this or things similar to this as well).

since dark-mode-pdf is not a native app (i.e., does not have access to your device's display apis) and relies on saving the result to a pdf, with the current transformation implementation i did a quick fix which is adding the option to use a customizable gradient tone for all the text/drawings instead of all white/gray. so it's going to be different shades of a single color that you select. it's not exactly like you want but still it's an improvement i think.

**Comment by jc9108** [comment]
example using the first pdf you provided,

old
![old](https://user-images.githubusercontent.com/31039318/172493207-7006b8f0-9d18-4e6e-8c6f-cd2ca7abd123.jpg)

new: using gradient tone
![new 1](https://user-images.githubusercontent.com/31039318/172493286-01ba2a55-a05d-4425-b16e-58cd0e76142e.jpg)

new: using gradient tone + non-white text color
![new 2](https://user-images.githubusercontent.com/31039318/172493310-4d98fa06-a3c2-46f9-8637-d7510bc0d034.jpg)
